### ISSUE TITLE
Ability to omit `--target` if bakefile only declares a single target

### ISSUE THREAD

**Issue by mobileoverlord** [ghitchens/bake#2]
If a bake file declares only one target the user should not be required to pass a target to run commands that require the target flag. The target should be determined as the default target.

**Comment by ghitchens** [comment]
It would be really cool if you could specify a default target in bakefile so you could have a main default target but still have alternate recipes.

**Comment by mobileoverlord** [comment]
I like this proposal. We could do something like this:

``` elixir
use Bake.Config

platform :nerves
default_target :bbb

target :bbb,
  recipe: "nerves/bbb"

target :rpi2,
  recipe: "nerves/rpi2"
```

or we could add it as an attribute to the target like this

``` elixir
target :bbb,
  recipe: "nerves/bbb",
  default: true
```

Should we always require a default target to be set in order to omit the `--target` flag?

**Comment by wsmoak** [comment]
I have a slight preference for `default_target`.  (Otherwise, what is the expected behavior when users copy and paste and end up with two targets that have `default: true`?)

Ideally you wouldn't have to specify a default if there is only one, but I could live with it either way.  We'll just make sure it's in the example code.

**Comment by mobileoverlord** [comment]
good point @wsmoak i think `default_target` is the way to go

**Comment by fhunleth** [comment]
I like it too. `default_target`, that is.

**Comment by mobileoverlord** [comment]
fixed in master

**Comment by ghitchens** [comment]
Looks great.
