### ISSUE TITLE
Error - crypto_callback.so: File format not recognized

### ISSUE THREAD

**Issue by santif** [ghitchens/bake#23]
After adding `cowboy` dependency, I'm getting the following error executing `bake firmware`:

```
$ bake firmware
=> Using project default target: rpi
=> Building firmware for target rpi
==> Using System: nerves/rpi-0.3.3
==> Using Toolchain: nerves-armv6-rpi-linux-gnueabi-linux-x86_64-v0.6.0
Shell environment updated for Nerves

Nerves version: 0.3.3
Nerves configuration: nerves_rpi_elixir_defconfig
Cross-compiler prefix: armv6-rpi-linux-gnueabi
Erlang/OTP release on target: 18.2.1
Elixir version: 1.3.0-dev
...
Consolidated Inspect
Building release with MIX_ENV=dev.
==> The release for hello2-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/hello2/bin/hello2 console`
Updating base firmware image with Erlang release...
/home/sfernandez/.nerves/toolchains/nerves-armv6-rpi-linux-gnueabi-linux-x86_64-v0.6.0/bin/armv6-rpi-linux-gnueabi-strip:/home/sfernandez/work/hello2/_nerves-tmp/rootfs-additions/srv/erlang/lib/crypto-3.6.2/priv/lib/crypto_callback.so: File format not recognized
```

Here are `mix.exs` and `Bakefile` files: https://gist.github.com/santif/1c93907262c9f8460076

**Comment by fhunleth** [comment]
That happens when `mix` is called instead of `bake` and creates a OTP release. The normal OTP release process copies shared libraries from your computer rather than the cross-compiled ones for the Raspberry Pi. Then at some later time when you called `bake`, firmware building step notices that something wasn't right with a shared library and gave the error message. A workaround is to delete the release and rerun `bake`.

**Comment by mobileoverlord** [comment]
Recently a change was pushed to bake which will force the release to be cleaned prior to building a new version using `bake firmware` You can update to the latest bake by calling `bake update` :bowtie:
